# Site settings
title: Mesird's Dev Blog
description: 'a personal iOS development blog'
url: 'http://mesird.com'
baseurl: '/mesird-blog/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mesird'
  email: mesird@126.com
  twitter_username: mesird
  facebook_username: holy_mesird
  github_username:  MESIRD
  linkedin_username:  杰-徐-95647a92

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
